language: python
python:
- '2.7'
sudo: false
cache:
  directories:
  - "~/.platformio"
install:
- pip install -U platformio
- platformio update
script:
- platformio run

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: ".pio/build/nodemcu-32s/firmware.bin"
  skip_cleanup: true
  overwrite: true
  draft: true
  all_branches: true
  
#  provider: releases
#  api_key: $GITHUB_TOKEN
#  file: ".pioenvs/nodemcu-32s/firmware.bin"
#  skip_cleanup: true
#  on:
#    tags: true

# provider: pages
# github_token: $GITHUB_TOKEN
# skip_cleanup: true
# keep_history: true
# verbose: true
# on:
#  branch: master
